sudo: required

language: generic

services:
  - docker

before_install:
  - echo "start creating an image with dockerfile"
  - docker build -t dong-woogie/docker-react-app -f Dockerfile.dev .

script:
  - docker run -e CI=true dong-woogie/docker-react-app npm run test -- --coverage

deploy:
  edge: true
  provider: elasticbeanstalk
  region: ap-northeast-2
  app: docker-react-app
  env: DocerReactApp-env
  bucket_name: elasticbeanstalk-ap-northeast-2-785720007930
  bucket_path: docker-react-app
  on:
    repo: dong-woogie/nodejs-docker-app
    branches:
      only:
        - master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: "$AWS_SECRET_ACCESS_KEY"
