sudo: required

language: generic

services:
  - docker

before_install:
  - echo "start creating an image with dockerfile"
  - docker build -t dong-woogie/docker-react-app -f Dockerfile.env .

script:
  - docker run -e CI=true dong-woogie/docker-react-app npm run test -- --coverage
after_success:
  - echo "Test Success"
